AllCops:
  Exclude:
    - vendor/**/*
    - metadata.rb

Metrics/AbcSize:
  Enabled: false
Next:
  Enabled: false
ClassLength:
  Enabled: false
Documentation:
  Enabled: false
Encoding:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
TrailingComma:
  EnforcedStyleForMultiline: comma
AlignParameters:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
BlockAlignment:
  Enabled: false
